language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

os:
  - linux
  - osx

before_install:
  - npm i -g npm@latest

cache:
  directories:
    - "node_modules"

sudo: false
after_script: "npm run coverage"
